version: '3.8'

services:
  fleetcontrol:
    image: fleetcontrol:latest
    build:
      context: .
      dockerfile: FleetControl.API/Dockerfile
    container_name: fleetcontrol-container
    networks:
      - rede-vps
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${SQLSERVER_CONNECTION_STRING}
      - MongoDbSettings__ConnectionString=${MONGODB_CONNECTION_STRING}
networks:
  rede-vps:
    external: true