name: FleetControl

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build da API
        run: dotnet build --configuration Release --no-restore

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      
          ls -la ~/.ssh
      
          ssh -v ${{ secrets.SERVER_USER }}@${{ secrets.SSH_HOST }} 'echo "SSH connection successful"'
      - name: Deploy application
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SSH_HOST }} << EOF

          cd ${{ secrets.PROJECT_DIRECTORY }}

          docker-compose down

          git pull origin master

          docker-compose up --build -d
          EOF
          
