name: FleetControl

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build da API
        run: dotnet build --configuration Release --no-restore

      - name: Executar os Testes
        run: dotnet test --configuration Release --no-build

      - name: Acessar o Servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIRECTORY }}

            if [ "$(docker ps -q -f name=minha-api-container)" ]; then
              echo "Parando e removendo container existente..."
              docker-compose down
            fi
            
            if [ ! -d ".git" ]; then
              echo "Repositório Git não encontrado, clonando..."
              git clone https://github.com/RodrigoSousa19/FleetControl.
            fi
            
            echo "Atualizando código da API..."
            git pull origin master

            echo "Subindo container..."
            docker-compose up --build -d
